-- ==========================================
-- NextGen Organics - Partial Fix Script
-- Run this in Supabase SQL Editor to fix missing tables
-- ==========================================

-- 1. TABLE: Categories (Missing)
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  slug text unique not null,
  image_url text,
  parent_id bigint references public.categories(id),
  created_at timestamp with time zone default now()
);

-- 2. TABLE: Products (Missing)
create table if not exists public.products (
  id uuid primary key default uuid_generate_v4(),
  vendor_id uuid references public.vendors(id) not null,
  category_id bigint references public.categories(id),
  
  name text not null,
  slug text unique not null,
  description text,
  price numeric not null,
  stock_quantity integer default 0,
  
  image_url text,
  gallery_images text, 
  
  product_type product_type default 'ORGANIC',
  approval_status product_approval_status default 'DRAFT',
  is_active boolean default true,
  
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 3. TABLE: Testimonials (Missing)
create table if not exists public.testimonials (
    id integer generated by default as identity primary key,
    role text,
    name text,
    location text,
    quote text,
    rating integer,
    is_featured boolean default true,
    created_at timestamp with time zone default now()
);


-- 4. Enable Row Level Security (RLS)
alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.testimonials enable row level security;

-- 5. RLS Policies

-- PRODUCTS
-- Public can view active published products
drop policy if exists "Public can view published products" on public.products;
create policy "Public can view published products" 
on public.products for select 
using (is_active = true and approval_status = 'PUBLISHED');

-- Vendor can manage their own products
drop policy if exists "Vendor can crud own products" on public.products;
create policy "Vendor can crud own products" 
on public.products for all 
using (
  auth.uid() in (
    select auth_user_id from public.vendors where id = vendor_id
  )
);

-- CATEGORIES
-- Public read access
drop policy if exists "Public can view categories" on public.categories;
create policy "Public can view categories" 
on public.categories for select 
using (true);

-- TESTIMONIALS
-- Public read access
drop policy if exists "Public can view testimonials" on public.testimonials;
create policy "Public can view testimonials" 
on public.testimonials for select 
using (true);

-- 6. Grant Access
grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;

-- Confirmation
select 'Tables created/verified successfully' as result;
