-- ==========================================
-- NextGen Organics - Supabase Setup Script
-- Run this in the Supabase SQL Editor
-- ==========================================

-- 1. Enable UUID Extension
create extension if not exists "uuid-ossp";

-- 2. Create Enums
create type vendor_status as enum ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED');
create type seller_category as enum ('NPOP_ORGANIC', 'NATURAL', 'ECO_FRIENDLY');
create type product_type as enum ('ORGANIC', 'NATURAL', 'ECO_FRIENDLY');
create type product_approval_status as enum ('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'REJECTED');

-- 3. Create Tables

-- TABLE: Vendors
create table public.vendors (
  id uuid primary key default uuid_generate_v4(),
  auth_user_id uuid references auth.users(id), -- Linked after approval
  
  business_name text not null,
  contact_email text unique not null,
  phone_number text,
  
  address_line text,
  city text,
  state text,
  pincode text,
  year_establishment text,
  
  seller_category seller_category default 'NPOP_ORGANIC',
  documents jsonb default '{}'::jsonb, -- Store Google Drive Links
  
  npop_number text,
  npop_validity date,
  npop_scope text,
  
  fssai_number text,
  fssai_validity date,
  fssai_type text,
  
  status vendor_status default 'PENDING',
  is_verified boolean default false,
  
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- TABLE: Categories
create table public.categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  slug text unique not null,
  image_url text,
  parent_id bigint references public.categories(id),
  created_at timestamp with time zone default now()
);

-- TABLE: Products
create table public.products (
  id uuid primary key default uuid_generate_v4(),
  vendor_id uuid references public.vendors(id) not null,
  category_id bigint references public.categories(id),
  
  name text not null,
  slug text unique not null,
  description text,
  price numeric not null,
  stock_quantity integer default 0,
  
  image_url text,
  gallery_images text, -- Dictionary or Comma Separation
  
  product_type product_type default 'ORGANIC',
  approval_status product_approval_status default 'DRAFT',
  is_active boolean default true,
  
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 4. Enable Row Level Security (RLS)
alter table public.vendors enable row level security;
alter table public.products enable row level security;
alter table public.categories enable row level security;

-- 5. RLS Policies

-- VENDORS
-- Anyone can register (INSERT)
create policy "Enable insert for public registration" 
on public.vendors for insert 
with check (true);

-- Vendor can view own profile
create policy "Vendor can view own profile" 
on public.vendors for select 
using (auth.uid() = auth_user_id);

-- PRODUCTS
-- Public can view active published products
create policy "Public can view published products" 
on public.products for select 
using (is_active = true and approval_status = 'PUBLISHED');

-- Vendor can manage their own products
create policy "Vendor can crud own products" 
on public.products for all 
using (
  auth.uid() in (
    select auth_user_id from public.vendors where id = vendor_id
  )
);

-- CATEGORIES
-- Public read access
create policy "Public can view categories" 
on public.categories for select 
using (true);

-- 6. Grant Access
grant usage on schema public to anon, authenticated;
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;

-- End of Script
