"use client";

import Link from "next/link";
import { ArrowLeft, Loader2, UploadCloud } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";

import { api } from "@/lib/api";
import { supabase } from "@/lib/supabaseClient";

export default function Register() {
  const router = useRouter();
  const [formData, setFormData] = useState({
    businessName: "",
    email: "",
    // password removed
    phone: "",
    address: "",
    city: "",
    state: "",
    pincode: ""
  });
  const [file, setFile] = useState<File | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleRegister(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError("");

    try {
      // 1. Upload Document if exists
      let documentUrl = "";
      if (file) {
        const fileExt = file.name.split('.').pop();
        const fileName = `${Date.now()}.${fileExt}`;
        const { error: uploadError } = await supabase.storage
          .from('vendor-docs')
          .upload(fileName, file);

        if (uploadError) throw uploadError;
        
        // Get Public URL
        const { data: { publicUrl } } = supabase.storage
          .from('vendor-docs')
          .getPublicUrl(fileName);
          
        documentUrl = publicUrl;
      }

      // 2. Submit Application (Backend only, no Auth User creation yet)
      await api.vendors.register({
        business_name: formData.businessName,
        contact_email: formData.email,
        phone_number: formData.phone,
        documents: { reg_cert: documentUrl }, 
        address_line: formData.address,
        city: formData.city,
        state: formData.state,
        pincode: formData.pincode
      });

      router.push("/login/vendor?registered=true");
    } catch (err: unknown) {
      console.error(err);
      setError((err as Error).message || "Registration failed");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-[#F5F5F0] flex relative overflow-hidden">
      {/* Left Side - Form */}
      <div className="w-full lg:w-1/2 flex flex-col justify-center p-8 lg:p-12 relative z-10 overflow-y-auto max-h-screen">
         <Link href="/login/vendor" className="text-[#4A6741] hover:text-[#262A2B] flex items-center gap-2 text-sm font-medium transition-colors mb-8">
            <ArrowLeft size={16} /> Back to Login
         </Link>

         <div className="max-w-md w-full mx-auto">
            <div className="mb-8">
               <h1 className="text-3xl font-bold text-[#262A2B] mb-2">Partner with NextGen</h1>
               <p className="text-[#262A2B]/60">Join our network of sustainable organic farmers.</p>
            </div>

            <form onSubmit={handleRegister} className="space-y-4">
               {error && (
                  <div className="p-3 rounded-lg bg-red-500/10 border border-red-500/20 text-red-600 text-sm font-medium">
                     {error}
                  </div>
               )}
               
               <div>
                  <label className="block text-sm font-bold text-[#262A2B] mb-1">Business / Farm Name</label>
                  <input required type="text" value={formData.businessName} onChange={e => setFormData({...formData, businessName: e.target.value})} className="w-full bg-white border border-[#262A2B]/10 rounded-xl px-4 py-3 text-[#262A2B] outline-none focus:border-[#4A6741]" placeholder="Prakruthi Farms" />
               </div>

               <div className="grid grid-cols-2 gap-4">
                   <div>
                      <label className="block text-sm font-bold text-[#262A2B] mb-1">Email</label>
                      <input required type="email" value={formData.email} onChange={e => setFormData({...formData, email: e.target.value})} className="w-full bg-white border border-[#262A2B]/10 rounded-xl px-4 py-3 text-[#262A2B] outline-none focus:border-[#4A6741]" placeholder="contact@farm.com" />
                   </div>
                   <div>
                      <label className="block text-sm font-bold text-[#262A2B] mb-1">Phone</label>
                      <input required type="tel" value={formData.phone} onChange={e => setFormData({...formData, phone: e.target.value})} className="w-full bg-white border border-[#262A2B]/10 rounded-xl px-4 py-3 text-[#262A2B] outline-none focus:border-[#4A6741]" placeholder="+91 98765 43210" />
                   </div>
               </div>

               {/* Password field removed - Credentials generated by Admin on approval */}

               <hr className="border-[#262A2B]/10 my-4"/>
               
               <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-bold text-[#262A2B] mb-1">Address</label>
                    <input required type="text" value={formData.address} onChange={e => setFormData({...formData, address: e.target.value})} className="w-full bg-white border border-[#262A2B]/10 rounded-xl px-4 py-3 text-[#262A2B] outline-none focus:border-[#4A6741]" placeholder="Plot No. 123, Green Valley" />
                  </div>
                  <div className="grid grid-cols-3 gap-4">
                     <input required type="text" value={formData.city} onChange={e => setFormData({...formData, city: e.target.value})} className="w-full bg-white border border-[#262A2B]/10 rounded-xl px-4 py-3 text-[#262A2B] outline-none focus:border-[#4A6741]" placeholder="City" />
                     <input required type="text" value={formData.state} onChange={e => setFormData({...formData, state: e.target.value})} className="w-full bg-white border border-[#262A2B]/10 rounded-xl px-4 py-3 text-[#262A2B] outline-none focus:border-[#4A6741]" placeholder="State" />
                     <input required type="text" value={formData.pincode} onChange={e => setFormData({...formData, pincode: e.target.value})} className="w-full bg-white border border-[#262A2B]/10 rounded-xl px-4 py-3 text-[#262A2B] outline-none focus:border-[#4A6741]" placeholder="PIN" />
                  </div>
               </div>

               <div className="pt-4">
                  <label className="block text-sm font-bold text-[#262A2B] mb-1">Documents (NPOP/FSSAI Cert)</label>
                  <div className="relative">
                    <input 
                        required 
                        type="file" 
                        accept=".pdf,.jpg,.jpeg,.png"
                        onChange={e => setFile(e.target.files?.[0] || null)} 
                        className="w-full bg-white border border-[#262A2B]/10 rounded-xl pl-4 pr-10 py-3 text-[#262A2B] outline-none focus:border-[#4A6741] file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-[#4A6741]/10 file:text-[#4A6741] hover:file:bg-[#4A6741]/20 transition-all cursor-pointer" 
                    />
                    <UploadCloud className="absolute right-4 top-1/2 -translate-y-1/2 text-[#262A2B]/40 pointer-events-none" size={18} />
                  </div>
                  <p className="text-xs text-[#262A2B]/40 mt-1">Upload your certification document (PDF/Image) for verification.</p>
               </div>
               
               <button 
                  type="submit" 
                  disabled={loading}
                  className="w-full bg-[#4A6741] text-white font-bold py-4 rounded-xl text-center hover:bg-[#3A5233] transition-all transform active:scale-95 disabled:opacity-70 flex items-center justify-center gap-2 mt-6"
               >
                  {loading && <Loader2 className="animate-spin" size={20} />}
                  {loading ? "Registering..." : "Submit Application"}
               </button>
            </form>
         </div>
      </div>

      {/* Right Side - Image */}
      <div className="hidden lg:block w-1/2 relative bg-[#262A2B]">
         {/* eslint-disable-next-line @next/next/no-img-element */}
         <img 
            src="https://images.unsplash.com/photo-1595855709940-5776ee4a4a1f?q=80&w=1200&auto=format&fit=crop" 
            alt="Organic Farming" 
            className="w-full h-full object-cover opacity-60"
         />
         <div className="absolute bottom-16 left-16 max-w-md text-white">
            <h2 className="text-3xl font-bold mb-4">Join the Movement</h2>
            <p className="text-white/80">Connect directly with customers who value quality. No middlemen, better margins.</p>
         </div>
      </div>
    </div>
  );
}
